seed: 42
precision: 16
model:
  vocab_size: 22234
  max_len: 32
  n_layers: 3
  d_model: 512
  n_heads: 8
  d_ff: 2048
  dropout: 0.1
  latent_dim: 16
  pad_idx: 0
data:
  data_root: /home/star/Yanjun/PolyUCourse/DeepSC/data
  train_pkl: /home/star/Yanjun/PolyUCourse/DeepSC/data/europarl/train_data.pkl
  val_pkl: /home/star/Yanjun/PolyUCourse/DeepSC/data/europarl/test_data.pkl
  vocab_json: /home/star/Yanjun/PolyUCourse/DeepSC/data/europarl/vocab.json
  channel: AWGN
  pad_idx: 0
  vocab_size: 60000
train:
  batch_size: 128
  lr: 0.0003
  warmup: 8000
  lr_type: inverse_sqrt
  epochs: 30
  lambda_mi: 0.0009
