# ===========================================================
# 文件: configs/finetune/base.yaml
# -----------------------------------------------------------
# 微调任务的基础配置 (默认值)
# 这些参数将被 configs/finetune.yaml 包含，并可以通过命令行覆盖
# ===========================================================

# --- 微调模式与目标 ---
mode: channel                # 默认迁移学习模式: 'channel' 或 'domain'
new_channel: AWGN            # (仅当 mode='channel' 时有效) 目标新信道名称, 必须是在 deepsc/models/channel.py 中注册的

# --- 微调超参数 ---
epochs: 5                    # 微调的总轮数
patience: 3                  # 早停的回合数 (多少个验证周期内指标没有提升)
min_delta: 0.001             # 早停的最小改进阈值 (BLEU 分数)
save_top_k: 3                # 保存表现最好的 K 个检查点

# --- 可选：微调特定的优化器/学习率参数 ---
# 如果微调需要不同的学习率或优化器设置，可以在这里定义
# 例如:
# optimizer:
#   lr: 1e-5 # 微调时使用更小的学习率
#   weight_decay: 0 # 微调时可能不需要权重衰减