# ---- Transformer 主体 ----
vocab_size: ${data.vocab_size}
max_len   : 32
n_layers  : 3        # 论文 Table I
d_model   : 512
n_heads   : 8
d_ff      : 2048
dropout   : 0.1

# ---- Channel Enc/Dec ----
latent_dim: 16       # 符合论文
pad_idx    : ${data.pad_idx}
