# ================================================================================
# 文件: /home/star/Yanjun/PolyUCourse/DeepSC-Fork/configs/train/awgn.yaml
# (已修改: 调整 lambda_mi, snr 范围, 添加 weight_decay, epsilon, mine_lr, 调整 lr_type)
# --------------------------------------------------------------------------------
batch_size: 128
# --- 学习率与优化器 ---
lr: 1e-4              # <--- 主网络学习率 (如果 lr_type=fixed) 或峰值 (如果 lr_type=inverse_sqrt)
lr_type: fixed        # <--- 默认改为 'fixed' 以匹配原始行为
warmup: 8000          # (仅当 lr_type='inverse_sqrt' 时有效) 预热步数
weight_decay: 5e-4    # <--- 添加主网络的 Weight Decay
adam_eps: 1e-8        # <--- 主网络的 Adam Epsilon
epochs: 30            # 主网络训练轮数

# --- MINE相关参数 ---
lambda_mi: 0.001      # <--- 互信息权重，大幅降低以接近官方的 0.0009
mine_lr: 1e-3         # <--- MINE 网络的学习率，调整为 1e-3
mine_adam_eps: 1e-8   # <--- MINE 网络的 Adam Epsilon (可选)
mine_update_freq: 1   # (仅 LitDeepSC 有效) MINE更新频率，设为 1 表示每步都尝试更新
mine_extra_steps: 1   # (仅 LitDeepSC 有效) 每次更新 MINE 的步数
mine_warmup: 0        # (仅 LitDeepSC 有效) 禁用 MINE 预热期
mine_epochs: 10       # (仅 TwoPhaseTrainer 有效) MINE 预训练轮数

# --- SNR范围 ---
snr_low: 5            # <--- 训练时随机采样的最低SNR(dB)，改为 5
snr_high: 10          # <--- 训练时随机采样的最高SNR(dB)，改为 10

# --- 梯度裁剪 ---
grad_clip: 1.0        # 梯度裁剪值 (现在主要用于 MINE)